// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Forex_Associate (Abbas Borji)

//@version=5
indicator('Multi Timeframe Stochastic RSI Screener', overlay=true)

////////////
// Inputs //

// Symbol, Flags, and Timeframes
symbol = input.symbol('EURUSD',  group = 'Symbol')

t01 = input.bool(true,  title = "", group = 'Timeframes', inline = 'tf1')
t02 = input.bool(true,  title = "", group = 'Timeframes', inline = 'tf2')
t03 = input.bool(true,  title = "", group = 'Timeframes', inline = 'tf3')

tf1 = input.timeframe(title='Timeframe 1', defval='15', group='Timeframes', inline = 'tf1')
tf2 = input.timeframe(title='Timeframe 2', defval='30', group='Timeframes', inline = 'tf2')
tf3 = input.timeframe(title='Timeframe 3', defval='180', group='Timeframes', inline = 'tf3')
////////////////////////////////////////////////////////////////////////////////////////////
candle = input(close, title='Candle State')
rsi_len = input.int(14, title = "RSI Length",     group = 'Stochastic RSI')
rsi_os  = input.float(30, title = "RSI Overbought", group = 'Stochastic RSI')
rsi_ob  = input.float(70, title = "RSI Oversold",   group = 'Stochastic RSI')
smoothKD = input.int(3, 'K & D  Smoothing', minval=1, group='Stochastic RSI')
lengthStoch = input.int(14, 'Stochastic Length', minval=1, group='Stochastic RSI')
stoch_low = input.int(20, title='Stoch Oversold Level', group='Stochastic RSI')
stoch_high = input.int(80, title='Stoch Overbought Level', group='Stochastic RSI')

//////////////////
// Functions //

// Get Only Symbol
only_symbol(symbol) => 
    array.get(str.split(symbol, ":"), 1)

// Calculations
calculate() =>
    
    rsi = ta.rsi(candle, rsi_len)
    k_value = ta.sma(ta.stoch(rsi, rsi, rsi, lengthStoch), smoothKD)
    d_value =  ta.sma(k_value, smoothKD)
    [math.round_to_mintick(candle), rsi, k_value, d_value]

////////////
// Security Calls //

[candle01, rsi01, k01, d01] = request.security(symbol, tf1, calculate())
[candle02, rsi02, k02, d02] = request.security(symbol, tf2, calculate())
[candle03, rsi03, k03, d03] = request.security(symbol, tf3, calculate())

////////////
// Arrays //

tfs   = array.new_string(0)
t_arr   = array.new_bool(0)
candle_arr  = array.new_float(0)
rsi_arr = array.new_float(0)
k_arr = array.new_float(0)
d_arr = array.new_float(0)
stringSymbol = only_symbol(symbol)

///////////
// Timeframes //

array.push(tfs, tf1)
array.push(tfs, tf2)
array.push(tfs, tf3)


///////////
// Flags //

array.push(t_arr, t01)
array.push(t_arr, t02)
array.push(t_arr, t03)

///////////
// Candle Values //

array.push(candle_arr, candle01)
array.push(candle_arr, candle02)
array.push(candle_arr, candle03)

/////////
// RSI Values//

array.push(rsi_arr, rsi01)
array.push(rsi_arr, rsi02)
array.push(rsi_arr, rsi03)

/////////
// K Values //

array.push(k_arr, k01)
array.push(k_arr, k02)
array.push(k_arr, k03)

/////////
// D Values //

array.push(d_arr, d01)
array.push(d_arr, d02)
array.push(d_arr, d03)



///////////
// Table //

var tbl = table.new(position.top_right, 5, 5, frame_color=color.navy, frame_width=1, border_width=2, border_color=color.new(color.white, 100))

if barstate.islast

    table.cell(tbl, 0, 0, stringSymbol,              text_halign = text.align_center, bgcolor = color.navy, text_color = color.white, text_size = size.small)
    table.merge_cells(tbl,0,0,4,0)
    table.cell(tbl, 0, 1, 'Symbol',     text_halign = text.align_center, bgcolor = color.navy, text_color = color.white, text_size = size.small)
    table.cell(tbl, 1, 1, 'Price',      text_halign = text.align_center, bgcolor = color.navy, text_color = color.white, text_size = size.small)
    table.cell(tbl, 2, 1, 'RSI',        text_halign = text.align_center, bgcolor = color.navy, text_color = color.white, text_size = size.small)
    table.cell(tbl, 3, 1, 'K Value',        text_halign = text.align_center, bgcolor = color.navy, text_color = color.white, text_size = size.small)
    table.cell(tbl, 4, 1, 'D Value',        text_halign = text.align_center, bgcolor = color.navy, text_color = color.white, text_size = size.small)

    for i = 0 to 2
        if array.get(t_arr, i)
        
            rsi_col  = array.get(rsi_arr, i) > rsi_ob    ? color.red   : array.get(rsi_arr, i) < rsi_os ? color.green : #aaaaaa
            k_col  = array.get(k_arr, i) > stoch_high    ? color.red   : array.get(k_arr, i) < stoch_low ? color.green : #aaaaaa
            d_col  = array.get(d_arr, i) > stoch_high    ? color.red   : array.get(d_arr, i) < stoch_low ? color.green : #aaaaaa
            str = array.get(tfs, i)
            if str.contains(array.get(tfs, i),"60")
                str := "1H"
            else if str.contains(array.get(tfs, i),"120")
                str := "2H"
            else if str.contains(array.get(tfs, i),"180")
                str := "3H"
            else if str.contains(array.get(tfs, i),"240")
                str := "4H"
            else if str.contains(array.get(tfs, i),"720")
                str := "12H"
            
            table.cell(tbl, 0, i + 2, str,               text_halign = text.align_center, bgcolor = #FFA500, text_color = color.navy, text_size = size.small)
            table.cell(tbl, 1, i + 2, str.tostring(array.get(candle_arr, i)),                  text_halign = text.align_center, bgcolor = #aaaaaa,    text_color = color.white, text_size = size.small)
            table.cell(tbl, 2, i + 2, str.tostring(array.get(rsi_arr, i), "#.##"),         text_halign = text.align_center, bgcolor = rsi_col,    text_color = color.white, text_size = size.small)
            table.cell(tbl, 3, i + 2, str.tostring(array.get(k_arr, i), "#.##"),         text_halign = text.align_center, bgcolor = k_col,    text_color = color.white, text_size = size.small)
            table.cell(tbl, 4, i + 2, str.tostring(array.get(d_arr, i), "#.##"),         text_halign = text.align_center, bgcolor = d_col,    text_color = color.white, text_size = size.small)